### ISSUE TITLE
(w02_t03) No Audio in the Slides

### ISSUE THREAD

**Issue by UgurKap** [automl-edu/AutoMLLecture#33]
There is no audio in the video after the introduction. I am accessing the website from Mozilla Firefox. I have also downloaded the file and checked if there are different audio tracks, but there does not seem to be one.

**Comment by mlindauer** [comment]
Hi,

Thank you for reporting this. I can confirm that there is no audio. Luckily we still have the audio tracks for that. We will fix this early next week.

Best,
Marius

**Comment by larskotthoff** [comment]
Is this an issue with the original video?

**Comment by larskotthoff** [comment]
To be clear, the video I have doesn't have this issue. You can simply download it again.

**Comment by mlindauer** [comment]
Yes, as I said that happened on our end and we still have the audio track for your video. The question is whether we now want to fix the old video or want to wait for the new iteration of the video. 

If I'm not wrong, the last video you sent me had only the updated first 30sec, right?

**Comment by larskotthoff** [comment]
I will record the updated version Tuesday.

**Comment by UgurKap** [comment]
I have checkted the website, current version has audio.
