### ISSUE TITLE
Possible School Assignment Artifact in Chp. 2 Exercise Sheet (Python)

### ISSUE THREAD

**Issue by UgurKap** [automl-edu/AutoMLLecture#35]
Hi,

In the tests, there is a test to check whether a file called "members.txt" is existent. I guess it is an artifact from an earlier design of the course or maybe from a test for school assignment.

Other tests seem to be okay.

**Comment by mlindauer** [comment]
Thanks for reporting.

@dengdifan @AndreBiedenkapp could you please look into this

**Comment by dengdifan** [comment]
Hi,

Thanks for the reporting, we have updated a fixed version of python exercise sheet in KI-Campus

**Comment by UgurKap** [comment]
Tried with the updated tests, everything seems to work as expected
