### ISSUE TITLE
W04 T03 Page 5 Formula overflow

### ISSUE THREAD

**Issue by dwoiwode** [automl-edu/AutoMLLecture#51]
The formula derivation for monotonic $\epsilon$-greedy policy improvement overflows on the bottom of the page with the current layout:
![image](https://user-images.githubusercontent.com/20955739/140838960-2e8d9383-64cf-4fc5-986b-c48b0b52c86a.png)

**Comment by mlindauer** [comment]
That's the wrong repo, right?

In fact, this is fixed in the latex source. I was still hoping for the automatic building after pushing changes from overleaf.

**Comment by dwoiwode** [comment]
Oh yeah sorry, looks like I messed up the repository. Should be in [RL_Lecture](https://github.com/automl-edu/RL_lecture).

Did you push the changes from overleaf to git? I cannot see them in the [history](https://github.com/automl-edu/RL_lecture/commits/1680c7281bfdf3ffebf953302de1ee21c506cfe9/w04_model_free_control/t03_exploration.tex) or in [git-blame](https://github.com/automl-edu/RL_lecture/blame/1680c7281bfdf3ffebf953302de1ee21c506cfe9/w04_model_free_control/t03_exploration.tex#L80).

Automatic building currently only works [here](https://github.com/dwoiwode/RL_lecture/pull/1), as this feature is WIP and currently being tested.

**Comment by mlindauer** [comment]
Now, I pushed these ;-)

**Comment by dwoiwode** [comment]
Oh okay 👍🏻 Sorry for the impatience
